import plot1 from "../assets/plot1.jpg";
import plot2 from "../assets/plot2.jpg";
import plot3 from "../assets/plot3.jpg";
import plot4 from "../assets/plot4.jpg";
import plot5 from "../assets/plot5.jpg";
import plot6 from "../assets/plot6.jpg";
import plot7 from "../assets/plot7.jpg";
import plot8 from "../assets/plot8.jpg";
import plot9 from "../assets/plot9.jpg";
import plot10 from "../assets/plot10.jpg";
import plot11 from "../assets/plot11.jpg";
import plot12 from "../assets/plot12.jpg";
import plot13 from "../assets/plot13.jpg";
import plot14 from "../assets/plot14.jpg";
import plot15 from "../assets/plot15.jpg";
import plot16 from "../assets/plot16.jpg";
import plot17 from "../assets/plot17.jpg";
import plot18 from "../assets/plot18.jpg";
import plot19 from "../assets/plot19.jpg";
import plot20 from "../assets/plot20.jpg";
import plot21 from "../assets/plot21.jpg";
import plot22 from "../assets/plot22.jpg";
import plot23 from "../assets/plot23.jpg";
import plot24 from "../assets/plot24.jpg";
import plot25 from "../assets/plot25.jpg";
import plot26 from "../assets/plot26.jpg";
import plot27 from "../assets/plot27.jpg";
import plot28 from "../assets/plot28.jpg";
import plot29 from "../assets/plot29.jpg";
import plot30 from "../assets/plot30.jpg";

const delay = (ms) => new Promise((res) => setTimeout(res, ms));

const Listings = [
  {
    id: 1,
    imageUrl: plot1,
    title: "5 Marla Plot for sale",
    address: "DHA Phase 1, Lahore",
    coveredAreaSQFT: 1250,
    propertyType: "PLOT",
    isCommercial: false,
    price: 2000000,
    beds: "",
    bath: "",
  },
  {
    id: 2,
    imageUrl: plot2,
    title: "10 Marla Plot for sale",
    address: "DHA Phase 2, Lahore",
    coveredAreaSQFT: 2250,
    propertyType: "PLOT",
    isCommercial: false,
    price: 3500000,
    beds: "",
    bath: "",
  },
  {
    id: 3,
    imageUrl: plot3,
    title: "15 Marla Plot for sale",
    address: "DHA Phase 3, Lahore",
    coveredAreaSQFT: 2750,
    propertyType: "PLOT",
    isCommercial: true,
    price: 4000000,
    beds: "",
    bath: "",
  },
  {
    id: 4,
    imageUrl: plot4,
    title: "20 Marla Plot for sale",
    address: "DHA Phase 4, Lahore",
    coveredAreaSQFT: 3250,
    propertyType: "PLOT",
    isCommercial: false,
    price: 4500000,
    beds: "",
    bath: "",
  },
  {
    id: 5,
    imageUrl: plot5,
    title: "25 Marla Plot for sale",
    address: "DHA Phase 5, Lahore",
    coveredAreaSQFT: 3750,
    propertyType: "PLOT",
    isCommercial: false,
    price: 5000000,
    beds: "",
    bath: "",
  },
  {
    id: 6,
    imageUrl: plot6,
    title: "30 Marla Plot for sale",
    address: "DHA Phase 6, Lahore",
    coveredAreaSQFT: 4250,
    propertyType: "PLOT",
    isCommercial: true,
    price: 5500000,
    beds: "",
    bath: "",
  },
  {
    id: 7,
    imageUrl: plot7,
    title: "35 Marla Plot for sale",
    address: "DHA Phase 7, Lahore",
    coveredAreaSQFT: 4750,
    propertyType: "PLOT",
    isCommercial: false,
    price: 6000000,
    beds: "",
    bath: "",
  },
  {
    id: 8,
    imageUrl: plot8,
    title: "40 Marla Plot for sale",
    address: "DHA Phase 8, Lahore",
    coveredAreaSQFT: 5250,
    propertyType: "PLOT",
    isCommercial: false,
    price: 6500000,
    beds: "",
    bath: "",
  },
  {
    id: 9,
    imageUrl: plot9,
    title: "3 Bedroom House for Sale",
    address: "Bahria Town, Lahore",
    beds: 3,
    bath: 3,
    coveredAreaSQFT: 1650,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 5500000,
  },
  {
    id: 10,
    imageUrl: plot10,
    title: "4 Bedroom House with Garden",
    address: "Model Town, Lahore",
    beds: 4,
    bath: 4,
    coveredAreaSQFT: 1850,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 6500000,
  },
  {
    id: 11,
    imageUrl: plot11,
    title: "5 Bedroom House with Pool",
    address: "Gulberg, Lahore",
    beds: 5,
    bath: 5,
    coveredAreaSQFT: 2500,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 7500000,
  },
  {
    id: 12,
    imageUrl: plot12,
    title: "6 Bedroom House in a Gated Community",
    address: "Ferozepur Road, Lahore",
    beds: 6,
    bath: 6,
    coveredAreaSQFT: 2800,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 8500000,
  },
  {
    id: 13,
    imageUrl: plot13,
    title: "Luxury 7 Bedroom Mansion",
    address: "Cantt, Lahore",
    beds: 7,
    bath: 7,
    coveredAreaSQFT: 3200,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 9500000,
  },
  {
    id: 14,
    imageUrl: plot14,
    title: "4 Bedroom House near Commercial Area",
    address: "Johar Town, Lahore",
    beds: 4,
    bath: 4,
    coveredAreaSQFT: 2000,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 6600000,
  },
  {
    id: 15,
    imageUrl: plot15,
    title: "5 Bedroom Modern House with Garage",
    address: "Izmir Town, Lahore",
    beds: 5,
    bath: 5,
    coveredAreaSQFT: 2300,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 7700000,
  },
  {
    id: 16,
    imageUrl: plot16,
    title: "Cozy 3 Bedroom House for Small Families",
    address: "Eden Gardens, Lahore",
    beds: 3,
    bath: 3,
    coveredAreaSQFT: 1600,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 5400000,
  },
  {
    id: 17,
    imageUrl: plot17,
    title: "5 Bedroom House with Spacious Lawn",
    address: "EME Society, Lahore",
    beds: 5,
    bath: 5,
    coveredAreaSQFT: 2700,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 8800000,
  },
  {
    id: 18,
    imageUrl: plot18,
    title: "Modern Design 6 Bedroom Villa",
    address: "Paragon City, Lahore",
    beds: 6,
    bath: 6,
    coveredAreaSQFT: 3000,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 9900000,
  },
  {
    id: 19,
    imageUrl: plot19,
    title: "3 Bedroom Cottage with Rooftop Garden",
    address: "Gulshan-e-Ravi, Lahore",
    beds: 3,
    bath: 3,
    coveredAreaSQFT: 1800,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 5700000,
  },
  {
    id: 20,
    imageUrl: plot20,
    title: "Centrally Located 4 Bedroom House",
    address: "Askari 10, Lahore",
    beds: 4,
    bath: 4,
    coveredAreaSQFT: 2100,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 6800000,
  },
  {
    id: 21,
    imageUrl: plot21,
    title: "2 Bedroom Compact House for Sale",
    address: "Valencia Town, Lahore",
    beds: 2,
    bath: 2,
    coveredAreaSQFT: 1500,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 5200000,
  },
  {
    id: 22,
    imageUrl: plot22,
    title: "6 Bedroom Mansion with Home Cinema",
    address: "Bahria Orchard, Lahore",
    beds: 6,
    bath: 7,
    coveredAreaSQFT: 3300,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 10200000,
  },
  {
    id: 23,
    imageUrl: plot23,
    title: "Renovated 4 Bedroom Old City House",
    address: "Inside Lahore Fort",
    beds: 4,
    bath: 4,
    coveredAreaSQFT: 2200,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 7000000,
  },
  {
    id: 24,
    imageUrl: plot24,
    title: "7 Bedroom Luxury Villa with Pool",
    address: "DHA Phase 9, Lahore",
    beds: 7,
    bath: 7,
    coveredAreaSQFT: 3500,
    propertyType: "HOUSE",
    isCommercial: true,
    price: 11000000,
  },
  {
    id: 25,
    imageUrl: plot25,
    title: "Classic Design 5 Bedroom House",
    address: "LDA Avenue, Lahore",
    beds: 5,
    bath: 5,
    coveredAreaSQFT: 2400,
    propertyType: "HOUSE",
    isCommercial: false,
    price: 7800000,
  },
  {
    id: 26,
    imageUrl: plot26,
    title: "8 Marla Plot for sale",
    address: "DHA Phase 6, Karachi",
    coveredAreaSQFT: 1800,
    propertyType: "PLOT",
    isCommercial: true,
    price: 3900000,
    beds: "",
    bath: "",
  },
  {
    id: 27,
    imageUrl: plot27,
    title: "12 Marla Plot for sale",
    address: "Clifton, Karachi",
    coveredAreaSQFT: 2700,
    propertyType: "PLOT",
    isCommercial: false,
    price: 4500000,
    beds: "",
    bath: "",
  },
  {
    id: 28,
    imageUrl: plot28,
    title: "14 Marla Plot in Prime Location",
    address: "DHA Phase 7, Karachi",
    coveredAreaSQFT: 3100,
    propertyType: "PLOT",
    isCommercial: true,
    price: 4800000,
    beds: "",
    bath: "",
  },
  {
    id: 29,
    imageUrl: plot29,
    title: "6 Marla Plot for sale",
    address: "Gulistan-e-Johar, Karachi",
    coveredAreaSQFT: 1350,
    propertyType: "PLOT",
    isCommercial: false,
    price: 3600000,
    beds: "",
    bath: "",
  },
  {
    id: 30,
    imageUrl: plot30,
    title: "7 Marla Residential Plot",
    address: "DHA Phase 8, Karachi",
    coveredAreaSQFT: 1550,
    propertyType: "PLOT",
    isCommercial: true,
    price: 3750000,
    beds: "",
    bath: "",
  },
];

export const fetchListings = () => {
  return delay(500).then(() => Listings);
};

export const fetchListingDetails = (id) => {
  const listing = Listings.find((listing) => listing.id === id);
  return delay(500).then(() => listing);
};
